exports.COMMENTS_5_STAR = [
  // 1-line short reviews
  "Super quality product! Exceeded my expectations.",
  "Very fast delivery. Packaging was super neat and secure.",
  "Awesome quality for this price range. 100% satisfied with Sancart!",
  "Exact same color and product as shown in images.",
  "Build quality is top notch. Highly recommended!",
  "Product feels premium and works smoothly.",
  "Value for money! Will definitely order again from Sancart.",
  "Very happy with this purchase. Prompt dispatch and safe handling.",
  "Super fast shipping. Item arrived in pristine condition.",
  "Completely satisfied! Quality is 10/10.",
  "Unbeatable quality at this price tag! Loved it.",
  "Delivered safely in just 2 days. 5 stars!",
  "Best shopping experience on Sancart so far. Excellent quality.",
  "Must buy item! Fits perfectly and looks super premium.",
  "Great quality, very responsive customer support.",
  "Top notch finishing. Received without any delay or hassle.",
  "Brilliant item. Exactly what I was searching for!",
  "Smooth purchase and lightning fast dispatch.",
  "Product matches the description 100%. Highly satisfied.",
  "Amazing build and elegant finish. 5 stars for sure!",

  // 2-line medium reviews
  "Bought this after recommendation from a friend, totally worth it!\nDelivered safely in just 2 days with great packaging.",
  "Material quality and finishing are outstanding.\nBest price available online. Sancart customer support is awesome.",
  "Original genuine item. Very happy with the product performance.\nPackaging was rock solid with multi-layer bubble wrap.",
  "Color and design are stunning. Looks even better in hand.\nSuperb product, will definitely recommend to my family and friends.",
  "Smooth transaction and prompt delivery right to my doorstep.\nProduct matches description accurately. Excellent buy!",
  "Finishing is immaculate. Perfectly suits my daily requirement.\nFast dispatch and prompt tracking updates via WhatsApp.",
  "Very good quality material used. Looks super durable and sleek.\nReceived within 48 hours of placing the order.",
  "Top class product. I was skeptical initially but Sancart delivered quality.\nSeamless shopping experience, definitely buying more items!",
  "Ordered this recently and I absolutely loved the overall build.\nFinish is robust and looks much more expensive than its price.",
  "Arrived well packaged with sealed security tape and outer box.\nThe product works flawlessly and build quality is rock solid.",
  "Prompt delivery and item condition was 100% pristine.\nVery comfortable to use and looks very trendy!",
  "Remarkable product quality and neat presentation.\nGot real-time delivery tracking alerts right to my phone.",
  "Sturdy, premium and very well designed for daily use.\nDelivered on the exact estimated date with zero hassle.",
  "Genuine seller and top notch product. No scratches or defects.\nCustomer service was quick to help with my query.",
  "Very happy with Sancart's curated collection.\nThis item exceeded expectations in terms of durability and style.",
  "Great attention to detail and premium materials throughout.\nArrived earlier than anticipated with safe courier handling.",
  "The build feels sturdy and lightweight at the same time.\nWill definitely come back to Sancart for more purchases.",
  "Excellent build quality and reliable performance so far.\nCustomer service team was polite and very supportive.",
  "Loved the clean aesthetics and solid touch.\nDelivered in perfect shape with robust carton protection.",
  "High end finishing and very practical in daily use.\nNo complaints whatsoever, full value for money!",
  "Looks even more attractive in real life than the website photos.\nVery satisfied with the purchase and delivery speed.",
  "The product quality is surprisingly good for this price bracket.\nQuick dispatch and smooth checkout experience.",
  "A must-have product for everyone looking for dependable quality.\nReceived in sealed brand packaging with all tags intact.",
  "Everything about this order was smooth from payment to delivery.\nTop tier quality, definitely recommending to colleagues.",
  "Superior build and very comfortable to handle.\nFeels like it will easily last for years of regular use.",

  // 3-line detailed reviews
  "I ordered this for my daily usage and I am really impressed with the build quality.\nDelivery was completed within 2 days with proper tracking updates.\nOverall, a 5-star product and fantastic service from Sancart!",
  "Solid build and very stylish design. Everything feels premium right from opening the box.\nThe customer support team was very responsive when I inquired about delivery status.\nWill recommend this to everyone looking for reliable quality products.",
  "Super fast shipping and the product received is 100% genuine.\nThe packaging ensured no scratches or damage during transit.\nWill certainly be a returning customer on Sancart for future purchases!",
  "I have been using this daily for the past 2 weeks and the performance is flawless.\nThe finish is sleek, modern and matches the photos shown on the website.\nDelivered safely ahead of the estimated schedule with great care.",
  "Exceptional quality for the money spent. It feels sturdy and very well assembled.\nSancart delivered it straight to my doorstep with zero hassles.\nHighly recommend this to anyone looking for genuine high quality items!",
  "The product exceeded all my expectations in terms of build and aesthetics.\nReceived constant shipping notifications until safe arrival.\nFive stars without hesitation for product quality and prompt service!",
  "I was comparing several options online before deciding to buy this one.\nThe finish, durability, and practical design make it worth every single rupee.\nArrived securely packed in pristine condition, very pleased with the experience!",
  "Outstanding product design with premium grade materials.\nTracking updates were accurate and courier reached safely on time.\nWill be recommending Sancart to all my family and friends for future buys.",
  "Super impressed with how sturdy and reliable this product feels.\nThe customer experience from order placement to unboxing was seamless.\nDefinite 5 stars for high build standards and prompt dispatch!",
  "I rarely write detailed reviews, but this item completely won me over.\nQuality is far better than competing products in the same price segment.\nDelivered in clean, damage-free packaging right on schedule.",
  "An absolute delight to unbox and use in daily routines.\nThe craftsmanship is clean with zero rough edges or manufacturing defects.\nSancart customer care also followed up to ensure smooth delivery.",
  "Remarkable value for money with high-grade components.\nOrdered two units and both arrived in immaculate condition within 48 hours.\nSuperb shopping experience, I am 100% satisfied with this purchase!"
];

exports.COMMENTS_4_STAR = [
  // 1-line short reviews
  "Good product for the price point. Recommended.",
  "Decent quality, delivered within 3 days.",
  "Overall good experience. Worth buying.",
  "Item reached safely in good condition. Satisfied.",
  "Nice build quality. Fits my daily requirement perfectly.",
  "Fast delivery and good product quality.",
  "Works as expected. No complaints so far.",
  "Decent packaging and fast dispatch.",
  "Good value for money. Sancart delivery was prompt.",
  "Nice product. Material feels good in hand.",
  "Satisfied with the purchase. Standard reliable quality.",
  "Delivered on time. Good product for regular use.",
  "Pretty good build and design. Fits my budget nicely.",
  "Solid product, met all basic expectations.",
  "Happy with the purchase. Good customer support.",

  // 2-line medium reviews
  "Product is good, packaging could be slightly better but item is great.\nSatisfied with the quality and overall finishing.",
  "Good value for money. Quality is nice for daily usage.\nTook about 3 days to arrive, overall happy with purchase.",
  "Pretty good product. Color is slightly darker than photos, but build is solid.\nDelivery was smooth and hassle-free.",
  "Nice item with premium feel. Fits well and works without any glitch.\nWould give 5 stars if delivery was 1 day faster.",
  "Build quality is solid and it looks very smart.\nMinor cosmetic box dent from courier handling, but item is 100% intact.",
  "Good genuine product. Sturdy and well finished.\nDelivered on time with clear SMS tracking.",
  "Happy with the item. Quality matches the price point.\nSancart customer support responded promptly to my tracking query.",
  "Functional, clean design and reliable build.\nTook 4 days to reach my location, otherwise a great purchase experience.",
  "Product is exactly as described and works smoothly.\nVery decent quality for this affordable range.",
  "Good experience overall. Item arrived safely.\nQuality is durable enough for regular daily usage.",
  "The build is solid and looks great in person.\nSlightly tight packaging, but product inside is pristine.",
  "Value for money purchase for sure. Works as expected.\nDelivery was on schedule and tracking was clear.",
  "Good material quality and well structured.\nMinor delay of 1 day in shipping, but item quality makes up for it.",
  "Comfortable to use and looks neat on my desk.\nHappy with the purchase and would recommend to others.",
  "Sturdy product that performs well in daily routines.\nArrived in good condition with basic protective wrapping.",
  "Decent performance and fair pricing from Sancart.\nOrder processing was quick and customer support was helpful.",
  "Good design and decent material thickness.\nWorks without issues, happy with this buy.",
  "Satisfied with how the product looks and functions.\nTook 3 days for delivery, overall positive experience.",
  "Nice aesthetic and decent durability for everyday use.\nNothing to complain about, solid 4-star product.",
  "Product fits description well and finish is good.\nWould definitely buy again if needed.",

  // 3-line detailed reviews
  "Received the item safely after 3 days of ordering.\nThe product quality is good and works well as advertised.\nPackaging was intact, though the outer box had slight courier handling marks.",
  "Decent purchase from Sancart! The product works smoothly and feels sturdy.\nDelivery was on time and order tracking was accurate.\nSlightly pricey compared to local market, but quality compensates for it.",
  "The product is well made and meets all my expectations for regular use.\nDelivered safely with adequate bubble wrap protection.\nGiving 4 stars mainly because delivery took 4 days instead of 2.",
  "Solid construction and neat design. Happy with the overall performance.\nSancart handled the order efficiently with clear notifications.\nGood option if you want reliable products at reasonable pricing.",
  "Product works as described and feels durable after several days of usage.\nCourier arrived safely with no internal damage.\nGood overall value for money and solid satisfaction.",
  "The item is very functional and build quality matches the description.\nDelivery took 3 days and updates were provided at every step.\nWould give full 5 stars if color was exact match to product photos.",
  "I have been using this item for over a week without any trouble.\nSturdy material and modern styling that suits daily needs.\nSatisfied with Sancart's prompt dispatch and order tracking system.",
  "Good product overall with dependable daily performance.\nPackaging had some slight courier scuffs, but internal bubble wrap kept it safe.\nDefinitely a reliable purchase for this price point.",
  "Good build quality and nice overall design aesthetic.\nIt handles daily usage smoothly without showing signs of wear.\nReasonable delivery timeline and polite delivery personnel.",
  "Solid 4-star experience with this purchase.\nThe product is well built and does exactly what it promises.\nCourier arrived on the 4th day in safe, sealed condition."
];

exports.COMMENTS_3_STAR = [
  // 1-line short reviews
  "Average product quality, but works fine for daily use.",
  "Product is OK. Delivery took 4 days to reach.",
  "Fair quality according to price. Nothing extraordinary.",
  "Decent product, but delivery took a day extra.",
  "Satisfactory performance for basic usage.",
  "Packaging was slightly crushed, but product inside is undamaged.",
  "Standard quality. Gets the job done for the price.",
  "Average item. Works fine but finishing could be improved.",
  "Acceptable quality, but expected slightly better material.",
  "It is okay for occasional use. Average build quality.",
  "Delivery was delayed by 2 days.",
  "Basic product with fair performance for the price point.",

  // 2-line medium reviews
  "Product quality is okayish for the price. Works as expected.\nDelivery took 5 days, expected slightly faster dispatch.",
  "Design is nice, but material feels lighter than expected.\nIt does the job, so keeping it for casual use.",
  "Average experience. The item is functional, but finishing could be better.\nCustomer support responded quickly to my delivery query though.",
  "The product is decent for the price, but build feels a bit lightweight.\nTook almost 5 days to reach my address.",
  "Works fine, but not as premium as shown in promotional images.\nReasonable for everyday budget usage.",
  "Delivery was slightly delayed, but product arrived safely.\nQuality is average, works without major issues.",
  "Item is okay for basic tasks. Doesn't feel high-end, but does the job.\nPackaging was quite basic without extra cushioning.",
  "Average build quality. Expected a slightly sturdier feel.\nCustomer service was polite when resolving my shipping query.",
  "The product does the job, but material is somewhat basic.\nDelivery took longer than expected, but arrived undamaged.",
  "Fair product for the price. Not extraordinary, but functional.\nPackaging could have used more bubble wrap for safety.",
  "Decent budget item for casual use.\nFinish has minor imperfections, but working condition is fine.",
  "Acceptable quality if you have basic requirements.\nTook 4 days to deliver with basic tracking updates.",
  "Average experience overall. Product is functional.\nExpected a heavier feel, but it serves basic daily purposes.",
  "The item works fine, but design could be more refined.\nDelivery was on time, so no complaints on logistics.",
  "A basic product with standard functionality.\nGood for budget conscious buyers, but not for heavy duty usage.",

  // 3-line detailed reviews
  "The product is acceptable for its budget price tag.\nMaterial quality is average and feels slightly lightweight in hand.\nDelivery took 5 days, though it arrived in one piece.",
  "Ordered this for everyday use and it performs at an average level.\nThe finishing has a few minor rough edges, but functionality is okay.\nWould recommend only if you are looking for an entry-level budget option.",
  "Delivery was slower than expected by 2 days.\nThe item works for basic usage, but does not give a premium feel.\nFair value for money if you manage your expectations.",
  "The product arrived in working condition after 4 days of transit.\nMaterial quality is acceptable for light use, but not very rugged.\nCustomer support was responsive when I asked about courier delays.",
  "An average purchase overall. The product functions as intended for simple tasks.\nThe packaging was minimal and the finish is somewhat plain.\nIt is fine if you just need a budget item without high expectations.",
  "Received the package after a 2-day delivery delay.\nThe product build is decent for the price, though slightly lighter than expected.\nAcceptable for everyday casual usage."
];
